![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

## Escribe el título del proyecto en Markdown
Titulo = "Fútbol de posesión, o no."

### TEMA

## Describe brevemente el tema del proyecto en Markdown
Tema  "La influencia de la posesión de balón en el fútbol"

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

## Escribe tu hipótesis principal en Markdown
Hipotesis_1  "La posesión de balón en el fútbol es uno de los factores mas determinantes en el resultado final"

# Escribe más hipótesis si las hubiera en Markdown
 Hipotesis_2 = "Partiendo de la posesión, los goles a favor y y el xG son los otros factores mas determinantes",                                        
 Hipotesis_3 = "La liga se encamina hacia un mayor'Valor de la posesión' (PV) "                                                                         
 Hipotesis_4 = "Si tuviese qu venderle este proyecto a un director deportivo, que haría?"

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [6]:
import pandas as pd
# guarda en variables los datasets y su fuente
df_1 = pd.read_csv('liga20.csv')
fuente_1 = "www.fbref.com"
df_2 = pd.read_csv('liga21.csv')
fuente_2 = "www.fbref.com"
df_3 = pd.read_csv('liga22.csv')
fuente_3 = "www.fbref.com"

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [5]:
# Primer dataset
df_1.head()

,Clasificacion,Equipo,GF,GC,Pts,xG,xGA,Posesion,Tiros a puerta,% Acierto pase,ACG,PV,Diferencia posesion
0,20,Eibar,29,52,30,45.2,45.7,49.3,127,69.9,48,37.86,-11.44
1,19,Valladolid,34,57,31,40.1,52.9,45.2,110,72.4,56,34.10,-11.10
2,18,Huesca,34,53,34,38.9,48.4,48.3,130,77.3,56,35.17,-13.13
3,17,Elche,34,55,36,29.9,60.9,47.5,86,79.0,54,25.07,-22.43
4,16,Alavés,36,57,38,42.6,49.9,42.8,95,71.0,59,30.29,-12.51

In [7]:
# Siguiente dataset...
df_2.head()

,Clasificacion,Equipo,GF,GC,Pts,xG,xGA,Posesion,Tiros a puerta,% Acierto pase,ACG,PV,Diferencia posesion
0,20,Alavés,31,65,31,37.3,57.0,42.0,111,68.3,48,31.19,-10.81
1,19,Levante,51,76,35,55.1,55.0,47.2,146,76.6,79,41.03,-6.17
2,18,Granada,44,61,38,39.0,61.2,44.7,131,71.1,68,31.54,-13.16
3,17,Cadiz,35,51,39,39.5,48.3,41.3,118,70.3,55,34.58,-6.72
4,16,Mallorca,36,63,39,38.8,49.3,45.3,131,73.5,59,35.50,-9.80

In [8]:
# Siguiente dataset...
df_3.head()

,Clasificacion,Equipo,GF,GC,Pts,xG,xGA,Posesion,Tiros a puerta,% Acierto pase,ACG,PV,Diferencia posesion
0,20,Elche,30,67,25,37.5,70.0,45.5,124,76.5,54,33.93,-11.57
1,19,Espanyol,52,69,37,48.3,59.8,43.1,151,73.7,84,35.53,-7.57
2,18,Valladolid,33,63,40,38.5,65.2,48.7,137,76.9,59,38.43,-10.27
3,17,Almería,49,65,41,45.5,62.5,45.1,155,76.6,76,35.82,-9.28
4,16,Valencia,42,45,42,49.3,43.5,52.0,141,77.7,62,48.53,-3.47